const palette = [
  {
    name: 'Neutral Gray',
    colors: [
      {id: 'n0', color: 'eceeed', name: 'Neutral Gray'},
      {id: 'n1', color: 'e2e3e5', name: 'Neutral Gray'},
      {id: 'n2', color: 'dadbdd', name: 'Neutral Gray'},
      {id: 'n3', color: 'd1d2d4', name: 'Neutral Gray'},
      {id: 'n4', color: 'bcbdc1', name: 'Neutral Gray'},
      {id: 'n5', color: 'a8a9ad', name: 'Neutral Gray'},
      {id: 'n6', color: '949599', name: 'Neutral Gray'},
      {id: 'n7', color: '77787c', name: 'Neutral Gray'},
      {id: 'n8', color: '636466', name: 'Neutral Gray'},
      {id: 'n9', color: '4c4d4f', name: 'Neutral Gray'},
      {id: 'n10', color: '312f30', name: 'Neutral Gray'},
      {id: '100', color: '312b2b', name: 'Black'},
      {id: '110', color: '030708', name: 'Special Black'}
    ]
  },
  {
    name: 'Blue',
    colors: [
      {id: 'b0000', color: 'f0f9fe', name: 'Pale Celestine'},
      {id: 'b000', color: 'e6f4f5', name: 'Pale Porcelain Blue'},
      {id: 'b00', color: 'ddf0f4', name: 'Frost Blue'},
      {id: 'b01', color: 'd6eef2', name: 'Mint Blue'},
      {id: 'b02', color: 'b3e3f1', name: 'Robins Egg Blue'},
      {id: 'b04', color: '73cfe6', name: 'Tahitian Blue'},
      {id: 'b05', color: '40c5e6', name: 'Process Blue'},
      {id: 'b06', color: '00b3e6', name: 'Peacok Blue'},
      {id: 'b12', color: 'c8e6f0', name: 'Ice Blue'},
      {id: 'b14', color: '71cfeb', name: 'Light Blue'},
      {id: 'b16', color: '00bcea', name: 'Cyanine Blue'},
      {id: 'b18', color: '1d8acb', name: 'Lapis Lazuli'},
      {id: 'b21', color: 'dbedf9', name: 'Baby Blue'},
      {id: 'b23', color: '92c2e8', name: 'Phthalo Blue'},
      {id: 'b24', color: '8acef3', name: 'Sky'},
      {id: 'b26', color: '65b3e3', name: 'Cobalt Blue'},
      {id: 'b28', color: '196db6', name: 'Royal Blue'},
      {id: 'b29', color: '0177c1', name: 'Ultramarine'},
      {id: 'b32', color: 'e2eff7', name: 'Pale Blue'},
      {id: 'b34', color: '82c3ed', name: 'Manganese Blue'},
      {id: 'b37', color: '156fa4', name: 'Antwerp Blue'},
      {id: 'b39', color: '2b64a9', name: 'Prussian Blue'},
      {id: 'b41', color: 'e2f0fb', name: 'Powder Blue'},
      {id: 'b45', color: '75c0ea', name: 'Smoky Blue'},
      {id: 'b52', color: 'adcddc', name: 'Soft Greenish Blue'},
      {id: 'b60', color: 'dae1f3', name: 'Pale Blue Gray'},
      {id: 'b63', color: 'a7bbe0', name: 'Light Hydrangea'},
      {id: 'b66', color: '6888c5', name: 'Clematis'},
      {id: 'b69', color: '2165ae', name: 'Stratospheric Blue'},
      {id: 'b91', color: 'd5e2eb', name: 'Pale Grayish Blue'},
      {id: 'b93', color: '95c1da', name: 'Light Crockery Blue'},
      {id: 'b95', color: '60c5cf', name: 'Light Grayish Cobalt'},
      {id: 'b97', color: '457a9a', name: 'Night Blue'},
      {id: 'b99', color: '0f547e', name: 'Agate'}
    ]
  },
  {
    name: 'Blue Green',
    colors: [
      {id: 'bg0000', color: 'eff8f3', name: 'Snow Green'},
      {id: 'bg000', color: 'e5f4ed', name: 'Pale Aqua'},
      {id: 'bg01', color: 'c7e6fa', name: 'Aqua Blue'},
      {id: 'bg02', color: 'c6e8ea', name: 'New Blue'},
      {id: 'bg05', color: '1db8ce', name: 'Holiday Blue'},
      {id: 'bg07', color: '1db8ce', name: 'Petroleum Blue'},
      {id: 'bg09', color: 'dcf0ef', name: 'Blue Green'},
      {id: 'bg10', color: 'dcf0ef', name: 'Cool Shadow'},
      {id: 'bg11', color: 'ceebf1', name: 'Moon White'},
      {id: 'bg13', color: 'c4e7e9', name: 'Mint Green'},
      {id: 'bg15', color: 'a0d9d2', name: 'Aqua'},
      {id: 'bg18', color: '37c0b0', name: 'Teal Blue'},
      {id: 'bg23', color: 'bde5dd', name: 'Coral Sea'},
      {id: 'bg32', color: 'bce2d7', name: 'Aqua Mint'},
      {id: 'bg34', color: 'a3dad7', name: 'Horizon Green'},
      {id: 'bg45', color: 'afdfdf', name: 'Nile Blue'},
      {id: 'bg49', color: '00b6b9', name: 'Duck Blue'},
      {id: 'bg53', color: 'accfd1', name: 'Ice Mint'},
      {id: 'bg57', color: '64bebe', name: 'Sketch Jasper'},
      {id: 'bg70', color: 'daecee', name: 'Ocean Mist'},
      {id: 'bg72', color: '74b8bb', name: 'Ice Ocean'},
      {id: 'bg75', color: '59918e', name: 'Abyss Green'},
      {id: 'bg78', color: '49706b', name: 'Bronze'},
      {id: 'bg90', color: 'bac1b9', name: 'Sketch Gray Sky'},
      {id: 'bg93', color: 'bac1b9', name: 'Green Gray'},
      {id: 'bg96', color: '81a291', name: 'Bush'},
      {id: 'bg99', color: '6e9b87', name: 'Flagstone Blue'}
    ]
  },
  {
    name: 'Green',
    colors: [
      {id: 'g0000', color: 'f1f7f3', name: 'Crystal Opal'},
      {id: 'g000', color: 'eaf5ed', name: 'Pale Green'},
      {id: 'g00', color: 'e3f2ed', name: 'Jade Green'},
      {id: 'g02', color: 'cfe8d3', name: 'Spectrum Green'},
      {id: 'g03', color: 'b6da9c', name: 'Meadow Green'},
      {id: 'g05', color: '69c07b', name: 'Emerald Green'},
      {id: 'g07', color: '7bc576', name: 'Nile Green'},
      {id: 'g09', color: '7ac465', name: 'Veronese Green'},
      {id: 'g12', color: 'd2e8c4', name: 'Sea Green'},
      {id: 'g14', color: '97cf90', name: 'Apple Green'},
      {id: 'g16', color: '60c198', name: 'Malachite'},
      {id: 'g17', color: '14b37d', name: 'Forest Green'},
      {id: 'g19', color: '2db98a', name: 'Bright Parrot Green'},
      {id: 'g20', color: 'edf6db', name: 'Wax White'},
      {id: 'g21', color: 'c4e4cd', name: 'Lime Green'},
      {id: 'g24', color: 'c3e0b4', name: 'Willow'},
      {id: 'g28', color: '119462', name: 'Ocean Green'},
      {id: 'g29', color: '197c5d', name: 'Pine Tree Green'},
      {id: 'g40', color: 'e4f1df', name: 'Dim Green'},
      {id: 'g43', color: 'd7e7a8', name: 'Various Pistachio'},
      {id: 'g46', color: '579e74', name: 'Sketch Mistletoe'},
      {id: 'g82', color: 'ccdab9', name: 'Spring Dim Green'},
      {id: 'g85', color: '9dc3aa', name: 'Verdigris'},
      {id: 'g94', color: '98a786', name: 'Grayish Olive'},
      {id: 'g99', color: '5f7e3a', name: 'Olive'}
    ]
  },
  {
    name: 'Yellow Green',
    colors: [
      {id: 'yg0000', color: 'f2f7e0', name: 'Lily White'},
      {id: 'yg00', color: 'e6e69e', name: 'Mimosa Yellow'},
      {id: 'yg01', color: 'e2ebb2', name: 'Green Bice'},
      {id: 'yg03', color: 'deeaaa', name: 'Yellow Green'},
      {id: 'yg05', color: 'd6e592', name: 'Salad'},
      {id: 'yg06', color: 'c4df92', name: 'Yellowish Green'},
      {id: 'yg07', color: 'a5cf4f', name: 'Acid Green'},
      {id: 'yg09', color: '82c566', name: 'Lettuce Green'},
      {id: 'yg11', color: 'e5f0d0', name: 'Mignonette'},
      {id: 'yg17', color: '72c156', name: 'Grass Green'},
      {id: 'yg21', color: 'f7f6be', name: 'Anise'},
      {id: 'yg23', color: 'e6eb8f', name: 'New Leaf'},
      {id: 'yg25', color: 'd0e17b', name: 'Celadon Green'},
      {id: 'yg41', color: 'd5ebd4', name: 'Pale Cobalt Green'},
      {id: 'yg45', color: 'b4dcb7', name: 'Cobalt Green'},
      {id: 'yg61', color: 'd6e9d6', name: 'Pale Moss'},
      {id: 'yg63', color: 'a0caa2', name: 'Pea Green'},
      {id: 'yg67', color: '81bf8c', name: 'Moss'},
      {id: 'yg91', color: 'dad7ae', name: 'Putty'},
      {id: 'yg93', color: 'd2d29c', name: 'Grayish Yellow'},
      {id: 'yg95', color: 'cbc65e', name: 'Pale Olive'},
      {id: 'yg97', color: '958f03', name: 'Spanish Olive'},
      {id: 'yg99', color: '4e6a15', name: 'Marine Green'}
    ]
  },
  {
    name: 'Yellow',
    colors: [
      {id: 'y0000', color: 'fefef4', name: 'Yellow Fluorite'},
      {id: 'y000', color: 'fffce9', name: 'Pale Lemon'},
      {id: 'y00', color: 'fefddf', name: 'Barium Yellow'},
      {id: 'y02', color: 'f6f396', name: 'Canary Yellow'},
      {id: 'y04', color: 'ede556', name: 'Acacia'},
      {id: 'y06', color: 'fef56c', name: 'Yellow'},
      {id: 'y08', color: 'fef200', name: 'Acid Yellow'},
      {id: 'y11', color: 'fffbcc', name: 'Pale Yellow'},
      {id: 'y13', color: 'fbf7ae', name: 'Lemon Yellow'},
      {id: 'y15', color: 'fee96c', name: 'Cadmium Yellow'},
      {id: 'y17', color: 'ffe455', name: 'Golden Yellow'},
      {id: 'y18', color: 'feed55', name: 'Lightning Yellow'},
      {id: 'y19', color: 'ffe93e', name: 'Napoli Yellow'},
      {id: 'y21', color: 'ffeec2', name: 'Buttercup Yellow'},
      {id: 'y23', color: 'fbe3b3', name: 'Yellowish Beige'},
      {id: 'y26', color: 'f0dd67', name: 'Mustard'},
      {id: 'y28', color: 'caa869', name: 'Lionet Gold'},
      {id: 'y32', color: 'f9dec0', name: 'Cashmere'},
      {id: 'y35', color: 'ffd879', name: 'Maize'},
      {id: 'y38', color: 'ffd274', name: 'Honey'}
    ]
  },
  {
    name: 'Orange',
    colors: [
      {id: 'yr0000', color: 'fff3e5', name: 'Pale Chiffon'},
      {id: 'yr00', color: 'fed6bd', name: 'Powder Pink'},
      {id: 'yr01', color: 'fedac2', name: 'Peach Puff'},
      {id: 'yr02', color: 'fcdcc5', name: 'Light Orange'},
      {id: 'yr04', color: 'fec369', name: 'Chrome Orange'},
      {id: 'yr07', color: 'f26f39', name: 'Cadmium Orange'},
      {id: 'yr09', color: 'f15524', name: 'Chinese Orange'},
      {id: 'yr12', color: 'ffe2a6', name: 'Loquat'},
      {id: 'yr14', color: 'fec84e', name: 'Caramel'},
      {id: 'yr15', color: 'fbb884', name: 'Pumpkin Yellow'},
      {id: 'yr16', color: 'feb729', name: 'Apricot'},
      {id: 'yr18', color: 'f26b3c', name: 'Sanguine'},
      {id: 'yr20', color: 'ffe1bf', name: 'Yellowish Shade'},
      {id: 'yr21', color: 'f5ddb1', name: 'Cream'},
      {id: 'yr23', color: 'eccf8b', name: 'Yellow Ochre'},
      {id: 'yr24', color: 'f0cf64', name: 'Pale Sepia'},
      {id: 'yr30', color: 'fef2da', name: 'Macadamia Nut'},
      {id: 'yr31', color: 'ffdea8', name: 'Light Reddish Yellow'},
      {id: 'yr61', color: 'fddac4', name: 'Spring Orange'},
      {id: 'yr65', color: 'faae60', name: 'Atoll'},
      {id: 'yr68', color: 'f37022', name: 'Orange'},
      {id: 'yr82', color: 'fdc68d', name: 'Mellow Peach'}
    ]
  },
  {
    name: 'Red',
    colors: [
      {id: 'r0000', color: 'fef3ef', name: 'Pink Beryl'},
      {id: 'r000', color: 'fef0e7', name: 'Cherry White'},
      {id: 'r00', color: 'feeae1', name: 'Pinkish White'},
      {id: 'r01', color: 'fde0d8', name: 'Pinkish Vanilla'},
      {id: 'r02', color: 'fdd3c7', name: 'Rose Salmon'},
      {id: 'r05', color: 'f6917b', name: 'Salmon Red'},
      {id: 'r08', color: 'f26754', name: 'Vermilion'},
      {id: 'r11', color: 'fde1d5', name: 'Pale Cherry Pink'},
      {id: 'r12', color: 'fcd3c1', name: 'Light Tea Rose'},
      {id: 'r14', color: 'f59b92', name: 'Light Rouge'},
      {id: 'r17', color: 'f4846c', name: 'Lipstick Orange'},
      {id: 'r20', color: 'fcd7cf', name: 'Blush'},
      {id: 'r21', color: 'fac1b6', name: 'Sardonyx'},
      {id: 'r22', color: 'f8b7b1', name: 'Light Prawn'},
      {id: 'r24', color: 'f27579', name: 'Prawn'},
      {id: 'r27', color: 'f15062', name: 'Cadmium Red'},
      {id: 'r29', color: 'ed174b', name: 'Lipstick Red'},
      {id: 'r30', color: 'fce3df', name: 'Pale Yellowish Pink'},
      {id: 'r32', color: 'fac1ba', name: 'Peach'},
      {id: 'r35', color: 'f27185', name: 'Coral'},
      {id: 'r37', color: 'e86c74', name: 'Carmine'},
      {id: 'r39', color: 'cb487a', name: 'Garnet'},
      {id: 'r43', color: 'ee848e', name: 'Bougainvillaea'},
      {id: 'r46', color: 'e04d69', name: 'Strong Red'},
      {id: 'r56', color: 'd27c95', name: 'Currant'},
      {id: 'r59', color: 'b74f70', name: 'Cardinal'},
      {id: 'r81', color: 'f1c8d6', name: 'Rose Pink'},
      {id: 'r83', color: 'f19cb9', name: 'Rose Mist'},
      {id: 'r85', color: 'd36a93', name: 'Rose Red'},
      {id: 'r89', color: '7d2b42', name: 'Dark Red'}
    ]
  },
  {
    name: 'Red Violet',
    colors: [
      {id: 'rv0000', color: 'f2eaf5', name: 'Evening Primrose'},
      {id: 'rv000', color: 'f4e2ee', name: 'Pale Purple'},
      {id: 'rv00', color: 'f1daea', name: 'Water Lily'},
      {id: 'rv02', color: 'fad5e6', name: 'Sugared Almond Pink'},
      {id: 'rv04', color: 'f6a3bf', name: 'Shock Pink'},
      {id: 'rv06', color: 'f386af', name: 'Cerise'},
      {id: 'rv10', color: 'fdecf4', name: 'Pale Pink'},
      {id: 'rv11', color: 'fbd6dd', name: 'Pink'},
      {id: 'rv13', color: 'f9c9d7', name: 'Tender Pink'},
      {id: 'rv14', color: 'f495b7', name: 'Begonia Pink'},
      {id: 'rv17', color: 'db7eb3', name: 'Deep Magenta'},
      {id: 'rv19', color: 'd268aa', name: 'Red Violet'},
      {id: 'rv21', color: 'fde8e7', name: 'Light Pink'},
      {id: 'rv23', color: 'f8bac9', name: 'Pure Pink'},
      {id: 'rv25', color: 'f493be', name: 'Dog Rose Flower'},
      {id: 'rv29', color: 'ef4880', name: 'Crimson'},
      {id: 'rv32', color: 'fad3ce', name: 'Shadow Pink'},
      {id: 'rv34', color: 'f9afae', name: 'Dark Pink'},
      {id: 'rv42', color: 'f8bbb6', name: 'Salmon Pink'},
      {id: 'rv52', color: 'f9cade', name: 'Various Cotton Candy'},
      {id: 'rv55', color: 'e9a5ca', name: 'Hollyhock'},
      {id: 'rv63', color: 'd09dae', name: 'Begonia'},
      {id: 'rv66', color: 'b86a84', name: 'Raspberry'},
      {id: 'rv69', color: '8b576e', name: 'Peony'},
      {id: 'rv95', color: 'b684a1', name: 'Baby Blossoms'},
      {id: 'rv99', color: '5a4858', name: 'Argyle Purple'}
    ]
  },
  {
    name: 'Violet',
    colors: [
      {id: 'v0000', color: 'f0edf6', name: 'Rose Quartz'},
      {id: 'v000', color: 'e9e5f3', name: 'Pale Heath'},
      {id: 'v01', color: 'e4c1d9', name: 'Heath'},
      {id: 'v04', color: 'e6aace', name: 'Lilac'},
      {id: 'v05', color: 'e2a6ca', name: 'Azalea'},
      {id: 'v06', color: 'ce95c2', name: 'Lavender'},
      {id: 'v09', color: '8754a1', name: 'Violet'},
      {id: 'v12', color: 'eed7e9', name: 'Pale Lilac'},
      {id: 'v15', color: 'd3a6cd', name: 'Mallow'},
      {id: 'v17', color: 'a092c7', name: 'Amethyst'},
      {id: 'v20', color: 'e2e0ed', name: 'Wisteria'},
      {id: 'v22', color: 'b2b1d0', name: 'Sketch Ash Lavender'},
      {id: 'v25', color: '857fad', name: 'Pale Blackberry'},
      {id: 'v28', color: '6b668e', name: 'Sketch Eggplant'},
      {id: 'v91', color: 'e8c4d0', name: 'Pale Grape'},
      {id: 'v93', color: 'e5c1db', name: 'Early Grape'},
      {id: 'v95', color: 'b77ca8', name: 'Light Grape'},
      {id: 'v99', color: '524358', name: 'Aubergine'}
    ]
  },
  {
    name: 'Blue Violet',
    colors: [
      {id: 'bv0000', color: 'eae7f2', name: 'Sketch Pale Thistle'},
      {id: 'bv000', color: 'eae7f2', name: 'Iridescent Mauve'},
      {id: 'bv00', color: 'e0dced', name: 'Mauve Shadow'},
      {id: 'bv01', color: 'c4c9e6', name: 'Viola'},
      {id: 'bv02', color: 'aab8db', name: 'Prune'},
      {id: 'bv04', color: '7c97ce', name: 'Blue Berry'},
      {id: 'bv08', color: 'eae7f2', name: 'Blue Violet'},
      {id: 'bv11', color: 'd4d2e8', name: 'Soft Violet'},
      {id: 'bv13', color: '8491c8', name: 'Hydrangea Blue'},
      {id: 'bv17', color: '6e84bd', name: 'Deep Reddish Blue'},
      {id: 'bv20', color: 'cfdbf1', name: 'Dull Lavender'},
      {id: 'bv23', color: 'b1c0dd', name: 'Grayish Lavender'},
      {id: 'bv25', color: '8184a7', name: 'Grayish Violet'},
      {id: 'bv29', color: '384558', name: 'Slate'},
      {id: 'bv31', color: 'eae7f2', name: 'Pale Lavender'},
      {id: 'bv34', color: '9fa7bc', name: 'Sketch Bluebell'}
    ]
  },
  {
    name: 'Earth',
    colors: [
      {id: 'e0000', color: 'fffaf4', name: 'Floral White'},
      {id: 'e000', color: 'fef5ee', name: 'Pale Fruit Pink'},
      {id: 'e00', color: 'fdf3ea', name: 'Cotton Pearl'},
      {id: 'e01', color: 'ffeee4', name: 'Pink Flamingo'},
      {id: 'e02', color: 'feece0', name: 'Fruit Pink'},
      {id: 'e04', color: 'e4bcc4', name: 'Lipstick Natural'},
      {id: 'e07', color: 'cc816a', name: 'Light Mahogany'},
      {id: 'e08', color: 'ca6553', name: 'Brown'},
      {id: 'e09', color: 'd96a4f', name: 'Burnt Sienna'},
      {id: 'e11', color: 'fee9d6', name: 'Barley Beige'},
      {id: 'e13', color: 'e9c5af', name: 'Light Suntan'},
      {id: 'e15', color: 'fbbb8d', name: 'Dark Suntan'},
      {id: 'e17', color: 'b85f57', name: 'Reddish Brass'},
      {id: 'e18', color: '88534d', name: 'Copper'},
      {id: 'e19', color: 'c45238', name: 'Redwood'},
      {id: 'e21', color: 'fde2c7', name: 'Soft Sun'},
      {id: 'e23', color: 'eccab1', name: 'Hazelnut'},
      {id: 'e25', color: 'd2a482', name: 'Caribe Cocoa'},
      {id: 'e27', color: '997663', name: 'Milk Chocolate'},
      {id: 'e29', color: '884636', name: 'Burnt Umber'},
      {id: 'e30', color: 'f7f0d6', name: 'Bisque'},
      {id: 'e31', color: 'f2e6ce', name: 'Brick Beige'},
      {id: 'e33', color: 'f3d2b1', name: 'Sand'},
      {id: 'e34', color: 'f0caa6', name: 'Toast'},
      {id: 'e35', color: 'e6c3a3', name: 'Chamois'},
      {id: 'e37', color: 'cc9159', name: 'Sepia'},
      {id: 'e39', color: 'c5743f', name: 'Leather'},
      {id: 'e40', color: 'f2e8dc', name: 'Brick White'},
      {id: 'e41', color: 'fef1e1', name: 'Pearl White'},
      {id: 'e42', color: 'f3ead9', name: 'Sand White'},
      {id: 'e43', color: 'e8dabd', name: 'Dull Ivory'},
      {id: 'e44', color: '8a6e59', name: 'Clay'},
      {id: 'e47', color: '8a6e59', name: 'Dark Brown'},
      {id: 'e49', color: '634c3c', name: 'Dark Bark'},
      {id: 'e50', color: 'f4ebf0', name: 'Egg Shell'},
      {id: 'e51', color: 'feecd6', name: 'Milky White'},
      {id: 'e53', color: 'f1dfb9', name: 'Raw Silk'},
      {id: 'e55', color: 'f1dfb9', name: 'Light Camel'},
      {id: 'e57', color: 'b18558', name: 'Light Walnut'},
      {id: 'e59', color: '9a7f6c', name: 'Walnut'},
      {id: 'e70', color: 'efeae6', name: 'Ash Rose'},
      {id: 'e71', color: 'a1847c', name: 'Champagne'},
      {id: 'e74', color: 'a1847c', name: 'Cocoa Brown'},
      {id: 'e77', color: '7f604e', name: 'Maroon'},
      {id: 'e79', color: '4a2c22', name: 'Cashew'},
      {id: 'e81', color: 'f0e6c2', name: 'Ivory'},
      {id: 'e84', color: 'ae9f80', name: 'Sketch Khaki'},
      {id: 'e87', color: '6f604d', name: 'Fig'},
      {id: 'e89', color: '5a4939', name: 'Sketch Pecan'},
      {id: 'e93', color: 'fed2b9', name: 'Tea Rose'},
      {id: 'e95', color: 'fcbc7e', name: 'Tea Orange'},
      {id: 'e97', color: 'b46034', name: 'Deep Orange'},
      {id: 'e99', color: 'b46034', name: 'Baked Clay'}
    ]
  },
  {
    name: 'Fluorescent',
    colors: [
      {id: 'frv1', color: 'f5a3c7', name: 'Fluorescent Pink'},
      {id: 'fv2', color: '7f74b6', name: 'Fluorescent Dull Violet'},
      {id: 'fy1', color: 'fff697', name: 'Fluorescent Yellow Orange'},
      {id: 'fyr1', color: 'fecc99', name: 'Fluorescent Orange'}
    ]
  },
  {
    name: 'Cool Gray',
    colors: [
      {id: 'c0', color: 'e0e7ed', name: 'Cool Gray'},
      {id: 'c1', color: 'dae3e8', name: 'Cool Gray'},
      {id: 'c2', color: 'ccd7dd', name: 'Cool Gray'},
      {id: 'c3', color: 'c1ccd2', name: 'Cool Gray'},
      {id: 'c4', color: '92a0ab', name: 'Cool Gray'},
      {id: 'c5', color: '92a0ab', name: 'Cool Gray'},
      {id: 'c6', color: '637079', name: 'Cool Gray'},
      {id: 'c7', color: '637079', name: 'Cool Gray'},
      {id: 'c8', color: '535d66', name: 'Cool Gray'},
      {id: 'c9', color: '3c474d', name: 'Cool Gray'},
      {id: 'c10', color: '202b31', name: 'Cool Gray'}
    ]
  },
  {
    name: 'Warm Gray',
    colors: [
      {id: 'w00', color: 'f3f3eb', name: 'Warm Gray'},
      {id: 'w0', color: 'ecece4', name: 'Warm Gray'},
      {id: 'w1', color: 'e7e7df', name: 'Warm Gray'},
      {id: 'w2', color: 'ddddd5', name: 'Warm Gray'},
      {id: 'w3', color: 'd2d2ca', name: 'Warm Gray'},
      {id: 'w4', color: 'bcbdb7', name: 'Warm Gray'},
      {id: 'w5', color: 'a8a9a4', name: 'Warm Gray'},
      {id: 'w6', color: '94958f', name: 'Warm Gray'},
      {id: 'w7', color: '777873', name: 'Warm Gray'},
      {id: 'w8', color: '63645f', name: 'Warm Gray'},
      {id: 'w9', color: '4c4d48', name: 'Warm Gray'},
      {id: 'w10', color: '302f2b', name: 'Warm Gray'}
    ]
  },
  {
    name: 'Toner Gray',
    colors: [
      {id: 't0', color: 'eceeed', name: 'Toner Gray'},
      {id: 't1', color: 'eaeae8', name: 'Toner Gray'},
      {id: 't2', color: 'e0e0de', name: 'Toner Gray'},
      {id: 't3', color: 'd1d2cc', name: 'Toner Gray'},
      {id: 't4', color: 'bcbbb9', name: 'Toner Gray'},
      {id: 't5', color: 'a8a7a3', name: 'Toner Gray'},
      {id: 't6', color: '949590', name: 'Toner Gray'},
      {id: 't7', color: '777674', name: 'Toner Gray'},
      {id: 't8', color: '63645f', name: 'Toner Gray'},
      {id: 't9', color: '4c4b49', name: 'Toner Gray'},
      {id: 't10', color: '322e2d', name: 'Toner Gray'}
    ]
  }
]

export {palette}
